### PR TITLE
[tech] Clean-up unused binaries

### PR DESCRIPTION
**Pull request by woshilapin**
This is cleanup once all binaries have been fully integrated into https://github.com/CanalTP/transit_model. All these PR must be merged and release first:
- [x] [feature] Add gtfs2ntfs binary CanalTP/transit_model#610
- [x] [feature] Add 'gtfs2netexfr' binary CanalTP/transit_model#611
- [x] [feature] Add 'ntfs2netexfr' binary CanalTP/transit_model#612
- [x] [feature] Add 'ntfs2ntfs' binary CanalTP/transit_model#613
- [x] [feature] Add 'ntfs2gtfs' binary CanalTP/transit_model#614

### CODE REVIEW

**Comment by woshilapin** [comment]
All related PR have been merged into `transit_model`. I'm removing the `do_not_merge` label.

**Comment by ArnaudOggy** [comment]
> All related PR have been merged into `transit_model`. I'm removing the `do_not_merge` label.

A bit dangerous to remove the label until we have communicated (as to DGITM)

**Comment by antoine-de** [comment]
we've integrated this change :+1: , but thanks a lot to think about us!

**Comment by ArnaudOggy** [comment]
@antoine-de 
> we've integrated this change +1 , but thanks a lot to think about us!
Need an official communication (from @prhod) or can we go?

**Comment by antoine-de** [comment]
hum I don't think its mandatory, but if you prefer you can send an official email

**Comment by antoine-de** [comment]
note: you should also update this wiki: https://wiki.lafabriquedesmobilites.fr/wiki/Gtfs2NetexFr

**Comment by woshilapin** [comment]
> note: you should also update this wiki: https://wiki.lafabriquedesmobilites.fr/wiki/Gtfs2NetexFr

I will ping Bertrand to make the modification.

**Comment by prhod** [comment]
@antoine-de (cc @woshilapin ) I wasn't thinking of an official mail to DGITM, only a message to the Navitia GoogleGroup. I only need time to write it :p 
Thanks for the link and the notice :+1:

**Pull request merged**
